import './style.css';

const heroes=[
 {id:'luma',name:'Luma Vértice',role:'Assalto',hp:110,color:'#ff5d7a',primary:'Carabina Prisma',secondary:'Pistola de Pulso',skill:'Impulso Orbital',ult:'Chuva Cromática',bio:'pilota rebelde espirituosa',str:'Dano e mobilidade',weak:'Pouca vida'},
 {id:'bram',name:'Bram Casco',role:'Tanque',hp:190,color:'#4cc9f0',primary:'Canhão Rebite',secondary:'Martelo Magnético',skill:'Muralha Portátil',ult:'Bastião Total',bio:'mecânico protetor',str:'Proteção de área',weak:'Alvo grande e lento'},
 {id:'nara',name:'Nara Pulso',role:'Suporte',hp:120,color:'#80ed99',primary:'Raio Sutura',secondary:'Dardo Sônico',skill:'Campo Reviva',ult:'Aurora Médica',bio:'médica irônica e brilhante',str:'Cura e buffs',weak:'Baixo dano'},
 {id:'io',name:'Ío Fagulha',role:'Defesa',hp:130,color:'#f9c74f',primary:'Lança-Bobinas',secondary:'Mina Luminosa',skill:'Torreta Mimo',ult:'Labirinto de Luz',bio:'inventora caótica',str:'Controle de rotas',weak:'Depende de preparo'},
 {id:'kael',name:'Kael Bruma',role:'Reconhecimento',hp:95,color:'#b517ff',primary:'Rifle Eco',secondary:'Lâmina Flash',skill:'Manto de Ruído',ult:'Mapa Fantasma',bio:'explorador sarcástico',str:'Flanqueio e visão',weak:'Frágil'}
];
const enemies=[
 {name:'Vigia de Latão',hp:45,type:'soldado',ai:'avança em grupo e procura cobertura'}, {name:'Olho Longo',hp:35,type:'atirador',ai:'mantém distância e mira em suportes'},
 {name:'Brutamonte Kappa',hp:130,type:'pesado',ai:'protege médicos e bloqueia corredores'}, {name:'Costureiro Zero',hp:55,type:'médico',ai:'recua e cura aliados'},
 {name:'Estilhaço',hp:30,type:'explosivo',ai:'corre em zigue-zague até explodir'}, {name:'Guardião Hex',hp:220,type:'mini-chefe',ai:'ergue escudos e invoca drones'}
];
const maps=[
 {id:'neon',name:'Mercado de Néon Maré',desc:'cidade portuária vertical com passarelas, vielas, docas e praça central'},
 {id:'lab',name:'Arquivo Subterrâneo Íris',desc:'laboratório secreto de corredores móveis e câmaras abertas'},
 {id:'desert',name:'Deserto das Antenas',desc:'cânion colorido com radares abandonados e trens de carga'}
];
const chapters=[
 {title:'Capítulo 1 — O Roubo da Cor',map:'Mercado de Néon Maré',main:'Recuperar o Núcleo Prisma antes que a Corporação Monólito apague a cidade.',side:'Salvar 3 técnicos e destruir antenas de propaganda.',boss:'Diretora Vanta',reward:'Kael desbloqueado e cosmético Jaqueta Aurora'},
 {title:'Capítulo 2 — Ecos no Arquivo',map:'Arquivo Subterrâneo Íris',main:'Descobrir por que a Monólito conhece as memórias dos heróis.',side:'Coletar fitas de origem de Luma e Bram.',boss:'Guardião Hex',reward:'Modo Eliminação'},
 {title:'Final — Coração Sem Cor',map:'Base Eclipse',main:'Derrotar Vanta e devolver criatividade às cidades-liga.',side:'Manter ao menos 2 heróis vivos.',boss:'Vanta Ascendente',reward:'Créditos e Nova Campanha+'}
];
let state={screen:'menu',hero:null,dead:{},hp:100,ammo:30,ult:0,objective:0,enemies:[],rooms:[],toast:'',mode:'historia',score:[0,0],bots:'NORMAL'};
const save=()=>localStorage.setItem('brigada-prisma',JSON.stringify({dead:state.dead,unlocked:heroes.map(h=>h.id),stats:{score:state.score}}));
const load=()=>{try{Object.assign(state,JSON.parse(localStorage.getItem('brigada-prisma'))||{})}catch{}};load();
function spawnMission(){state.enemies=enemies.slice(0,5).map((e,i)=>({...e,hp:e.hp,x:15+i*13,y:18+(i%3)*18}));state.objective=0;state.mode='historia';}
function render(){document.querySelector('#app').innerHTML=`<main class="${state.screen}">${screens[state.screen]()}</main>`;bind();}
const heroCard=h=>`<button class="card" data-pick="${h.id}" ${state.dead[h.id]?'disabled':''} style="--c:${h.color}"><b>${h.name}</b><span>${h.role}</span><small>${state.dead[h.id]?'MORTO / INDISPONÍVEL':'DISPONÍVEL'} • ${h.primary}</small><em>${h.skill} • ULT: ${h.ult}</em></button>`;
const screens={
 menu:()=>`<section class="hero"><h1>BRIGADA PRISMA</h1><p>Hero-shooter FPS cartunesco original: heróis rivais unem forças contra a Corporação Monólito, que transforma cidades em blocos sem cor.</p><button data-go="select">JOGAR / Modo História</button><button data-go="online">Online</button><button data-go="codex">Personagens, Arsenal e História</button><button data-go="settings">Configurações</button></section>`,
 select:()=>`<h2>PERSONAGENS DISPONÍVEIS</h2><div class="grid">${heroes.map(heroCard).join('')}</div><p class="hint">Mortes na campanha persistem até reiniciar a missão. Sobreviventes seguem para a próxima parte.</p><button data-reset>Reiniciar missão</button><button data-go="menu">Voltar</button>`,
 play:()=>`<canvas id="game" width="960" height="540"></canvas><section class="hud"><b>${state.hero.name}</b><span>Vida ${state.hp}/${state.hero.hp}</span><span>Munição ${state.ammo}</span><span>Habilidade: ${state.hero.skill}</span><span>Ultimate ${state.ult}%</span><span>Objetivo: ${chapters[0].main}</span><span>Placar Prisma ${state.score[0]} x ${state.score[1]} Monólito</span></section><p class="hint">WASD move, clique atira, E habilidade, Q ultimate. Protótipo local com IA, bots e troca de herói.</p>`,
 online:()=>`<h2>Online</h2><div class="split"><section><h3>Entrar em uma sala</h3>${rooms().map(r=>`<button class="room"><b>${r.name}</b><span>${r.map} • ${r.mode} • ${r.players}/${r.max} jogadores • ${r.bots} bots ${r.diff} • ${r.ping}ms • ${r.status}</span></button>`).join('')}</section><section><h3>Criar sala</h3><label>Nome <input id="roomName" value="Sala Prisma"></label><label>Mapa <select><option>Mercado de Néon Maré</option><option>Arquivo Subterrâneo Íris</option></select></label><label>Modo <select><option>Dominação</option><option>Carga</option><option>Deathmatch em Equipe</option><option>Captura</option><option>Eliminação</option></select></label><label>Bots <input type="number" value="6"></label><label>Dificuldade <select id="diff"><option>FÁCIL</option><option>NORMAL</option><option>DIFÍCIL</option><option>EXTREMO</option></select></label><label>Senha <input placeholder="opcional"></label><button data-create>Criar sala</button></section></div><button data-go="menu">Voltar</button>`,
 codex:()=>`<h2>Codex</h2><div class="grid">${heroes.map(h=>`<article class="card" style="--c:${h.color}"><h3>${h.name}</h3><p>${h.bio}. Forte: ${h.str}. Fraco: ${h.weak}.</p><p>Armas: ${h.primary} / ${h.secondary}. Sons próprios, falas rivais e animações de corrida, pulo, recarga, vitória e derrota.</p></article>`).join('')}</div><h2>Campanha</h2>${chapters.map(c=>`<article><h3>${c.title}</h3><p>${c.map}: ${c.main}</p><p>Secundário: ${c.side}. Chefe: ${c.boss}. Recompensa: ${c.reward}.</p></article>`).join('')}<h2>IA inimiga</h2>${enemies.map(e=>`<p><b>${e.name}</b> (${e.type}): ${e.ai}; detecta, persegue, recua e coordena habilidades.</p>`).join('')}<button data-go="menu">Voltar</button>`,
 settings:()=>`<h2>Configurações e salvamento</h2><p>Salvamento automático: campanha, missões, desbloqueios, cosméticos, configurações e estatísticas.</p><button data-save>Salvar agora</button><button data-go="menu">Voltar</button>`
};
function rooms(){return state.rooms.length?state.rooms:[{name:'Doca Relâmpago',map:'Mercado de Néon',mode:'Dominação',players:4,max:10,bots:6,diff:'NORMAL',ping:38,status:'Aguardando'},{name:'Carga do Eclipse',map:'Deserto das Antenas',mode:'Carga',players:8,max:12,bots:2,diff:'DIFÍCIL',ping:61,status:'Em andamento'}]}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.go;render()});document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{state.hero=heroes.find(h=>h.id===b.dataset.pick);state.hp=state.hero.hp;spawnMission();state.screen='play';render();loop()});document.querySelector('[data-reset]')?.addEventListener('click',()=>{state.dead={};save();render()});document.querySelector('[data-save]')?.addEventListener('click',()=>{save();alert('Salvo!')});document.querySelector('[data-create]')?.addEventListener('click',()=>{state.rooms.push({name:document.querySelector('#roomName').value,map:'Mercado de Néon',mode:'Dominação',players:1,max:12,bots:6,diff:document.querySelector('#diff').value,ping:0,status:'Lobby privado/público configurável'});render()});}
function loop(){const c=document.querySelector('#game');if(!c)return;const x=c.getContext('2d');let t=0;function frame(){if(!document.querySelector('#game'))return;t++;x.fillStyle='#111827';x.fillRect(0,0,960,540);x.fillStyle='#243b55';for(let i=0;i<8;i++)x.fillRect(i*130,80+(i%2)*90,80,210);x.fillStyle=state.hero.color;x.beginPath();x.arc(480,270,16,0,7);x.fill();state.enemies.forEach(e=>{e.x+=Math.sin(t/25+e.x)*.25;e.y+=Math.cos(t/30+e.y)*.2;x.fillStyle=e.type==='mini-chefe'?'#ef233c':'#f77f00';x.fillRect(e.x*8,e.y*5,28,28);x.fillStyle='white';x.fillText(e.name,e.x*8-12,e.y*5-5)});x.strokeStyle='#fff';x.beginPath();x.moveTo(470,270);x.lineTo(490,270);x.moveTo(480,260);x.lineTo(480,280);x.stroke();requestAnimationFrame(frame)}frame();}
window.addEventListener('keydown',e=>{if(state.screen!=='play')return;if(e.key==='e'){state.hp=Math.min(state.hero.hp,state.hp+20);state.ult+=10} if(e.key==='q'&&state.ult>=100){state.enemies=[];state.ult=0;state.score[0]+=5} if(e.key==='k'){die()}});
window.addEventListener('click',()=>{if(state.screen==='play'){state.ammo--;state.ult=Math.min(100,state.ult+7);state.enemies.pop(); if(!state.enemies.length){state.score[0]+=1;save();alert('Missão concluída! Reviravolta: Vanta era financiada pelo Conselho Prisma.');state.screen='menu';render()}}});
function die(){state.dead[state.hero.id]=true;save();alert(`${state.hero.name} caiu. Escolha outro personagem para continuar.`); if(heroes.every(h=>state.dead[h.id])){alert('Todos os personagens foram eliminados. Tentativa perdida.');state.dead={};}state.screen='select';render()}
render();
